const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
class E{constructor(tag='div'){this.tag=tag;this.children=[];this.value='';this.textContent='';this.disabled=false;this.events={};this.open=false;this.isConnected=true;this.focused=false;this.classes=new Set();this.classList={add:(...c)=>c.forEach(x=>this.classes.add(x)),remove:(...c)=>c.forEach(x=>this.classes.delete(x)),toggle:(x,on)=>on?this.classes.add(x):this.classes.delete(x)};}append(...x){this.children.push(...x)}replaceChildren(...x){this.children=x}addEventListener(k,fn){this.events[k]=fn}setAttribute(k,v){this[k]=v}showModal(){this.open=true}close(){this.open=false}scrollIntoView(){}focus(){this.focused=true}getBoundingClientRect(){return {left:10,top:10,right:100,bottom:100}}}
function setup(){let el={};let requests=[];let mode='normal';const catalog=[{chat_id:'1001',name:'same',type:'MultiChat',member_count:4},{chat_id:'1002',name:'same',type:'MultiChat',member_count:7},{chat_id:'1003',name:'owner',type:'MemoChat',member_count:1},{chat_id:'1004',name:'<img onerror=alert(1)>',type:'MultiChat',member_count:2}];let registered=[];let hold;
 const document={getElementById:id=>el[id]??(el[id]=new E()),createElement:t=>new E(t),querySelectorAll:()=>[],hidden:false};
 const fetch=async(url,opt={})=>{requests.push({url,opt});if(url==='/api/rooms/remove'){if(mode==='remove-loading')await new Promise(r=>hold=r);if(mode==='remove-error')return {ok:false,status:503,json:async()=>({reason:'unavailable'})};if(mode==='remove-held')return {ok:true,json:async()=>({removed:false,status:'held'})};}if(url==='/api/rooms/available'){if(mode==='loading')await new Promise(r=>hold=r);if(mode==='error')return {ok:false,status:503,json:async()=>({reason:'account_mismatch'})};if(mode==='stale')return {ok:true,json:async()=>({status:'held',reason:'catalog_stale'})};return {ok:true,json:async()=>({status:'ready',transport:'loco',rooms:mode==='empty'?[]:catalog.map(x=>({...x,registered:registered.includes(x.chat_id),approved:registered.includes(x.chat_id)})),sync_status:mode==='pending'?'pending':'ready'})};}if((url==='/api/rooms/add'||url==='/api/rooms')&&mode==='quota')return {ok:true,json:async()=>({[url==='/api/rooms/add'?'added':'updated']:false,status:'held',reason:'room_limit_reached',limit:100})};if(url==='/api/rooms/add'){const body=JSON.parse(opt.body);registered.push(body.chat_id);return {ok:true,json:async()=>({added:true,sync_status:mode==='pending'?'pending':'ready'})};}return {ok:true,json:async()=>({updated:true,removed:true})};};
 const context=vm.createContext({document,fetch,console,location:{hash:'',pathname:'/'},URLSearchParams,sessionStorage:{getItem:()=>'',setItem(){}},history:{replaceState(){}},setInterval(){},Date,confirm:()=>true});
 let source=fs.readFileSync(path.resolve(__dirname,'board.js'),'utf8').replace("refresh();setInterval(()=>","setInterval(()=>");vm.runInContext(source,context);vm.runInContext("refresh=async()=>{};roomsData={rooms:[],yumi_configured:true,transport:'loco'};",context);
 const run=code=>vm.runInContext(code,context);return {el,requests,run,mode:x=>mode=x,release:()=>hold(),catalog};}
const text=e=>e.textContent+' '+e.children.map(text).join(' ');
test('opens and auto loads without events; duplicate names stay distinct',async()=>{const f=setup();await f.el['open-add-room'].events.click();await new Promise(r=>setImmediate(r));assert.equal(f.el['add-room'].open,true);assert.ok(text(f.el['available-rooms']).includes('ID 1002'));assert.equal(f.requests.filter(r=>r.url==='/api/rooms/available').length,1);assert.equal(f.requests.filter(r=>r.opt.method==='POST').length,0);});
test('exact ID add excludes title and refreshes catalog',async()=>{const f=setup();await f.run('loadAvailable()');await f.run('addRoom(availableRooms[1])');const sent=JSON.parse(f.requests.find(r=>r.url==='/api/rooms/add').opt.body);assert.deepEqual(sent,{chat_id:'1002',yui:true,yumi:true});assert.ok(text(f.el['available-rooms']).includes('등록됨'));});
test('ID filter and MemoChat label',async()=>{const f=setup();await f.run('loadAvailable()');f.el['room-search'].value='1003';f.run('drawAvailable()');const s=text(f.el['available-rooms']);assert.ok(s.includes('나와의 채팅'));assert.ok(!s.includes('ID 1001'));});
test('name injection is literal text only',async()=>{const f=setup();await f.run('loadAvailable()');assert.ok(text(f.el['available-rooms']).includes('<img onerror=alert(1)>'));const tags=e=>[e.tag,...e.children.flatMap(tags)];assert.ok(!tags(f.el['available-rooms']).includes('img'));});
test('loading disables selection and refresh then restores',async()=>{const f=setup();f.mode('loading');const p=f.run('loadAvailable()');assert.equal(f.el['load-rooms'].disabled,true);assert.ok(text(f.el['available-rooms']).includes('불러오는 중'));f.release();await p;assert.equal(f.el['load-rooms'].disabled,false);});
test('failed reload clears previous clickable catalog; account error explained',async()=>{const f=setup();await f.run('loadAvailable()');f.mode('error');await f.run('loadAvailable()');assert.equal(f.run('availableRooms.length'),0);assert.ok(f.el['add-room-status'].textContent.includes('계정 연결'));});
test('empty and stale states have no add targets',async()=>{const f=setup();f.mode('empty');await f.run('loadAvailable()');assert.ok(text(f.el['available-rooms']).includes('확인된 채팅방이 없어요'));f.mode('stale');await f.run('loadAvailable()');assert.ok(f.el['add-room-status'].textContent.includes('동기화'));assert.equal(f.run('availableRooms.length'),0);});
test('pending after add is saved state and never retries',async()=>{const f=setup();f.mode('pending');await f.run('loadAvailable()');await f.run('addRoom(availableRooms[0])');assert.ok(f.el['add-room-status'].textContent.includes('승인은 저장됐고'));assert.equal(f.requests.filter(r=>r.url==='/api/rooms/add').length,1);});
test('delete only submits registry key; approval update submits existing exact key',async()=>{const f=setup();f.run("removeRoom({key:'synthetic-key',title:'same'})");await f.run('confirmRemoval()');let r=f.requests.find(r=>r.url==='/api/rooms/remove');assert.deepEqual(JSON.parse(r.opt.body),{key:'synthetic-key'});await f.run("save({key:'synthetic-key',approved:true,yui:true,yumi:true},{approved:false})");r=f.requests.find(r=>r.url==='/api/rooms');assert.equal(JSON.parse(r.opt.body).approved,false);});

test('quota add rejection explains limit and does not register or retry',async()=>{const f=setup();await f.run('loadAvailable()');f.mode('quota');await f.run('addRoom(availableRooms[0])');assert.ok(f.el['add-room-status'].textContent.includes('100개'));assert.ok(f.el['add-room-status'].textContent.includes('승인을 해제'));assert.ok(!f.el['add-room-status'].textContent.includes('추가했어요'));assert.equal(f.requests.filter(r=>r.url==='/api/rooms/add').length,1);await f.run('loadAvailable()');assert.equal(f.run('availableRooms[0].registered'),false);});
test('quota approval rejection preserves row permission and refreshes after restoring checkbox',async()=>{const f=setup();f.mode('quota');f.run(`var rejectedRoom={key:'quota-key',title:'same',conversation_id:'1002',provider:'kakao',account:'synthetic',transport:'loco',chat_id:'1002',approved:false,yui:false,yumi:false,recorded_calls:0};roomsData={rooms:[rejectedRoom],yumi_configured:true,transport:'loco',answer_unapproved_rooms:false};drawRooms(roomsData);var refreshCalls=0;refresh=async()=>{refreshCalls++;};`);const checkbox=f.el.rooms.children[0].children[2].children[0];checkbox.checked=true;await f.run('save(rejectedRoom,{approved:true,yui:true})');assert.equal(f.run('rejectedRoom.approved'),false);assert.equal(f.run('rejectedRoom.yui'),false);assert.equal(f.el.rooms.children[0].children[2].children[0].checked,false);assert.equal(f.run('refreshCalls'),1);assert.ok(f.el['error-notice'].textContent.includes('100개'));assert.ok(f.el['error-notice'].classes.has('error'));assert.ok(!f.el['error-notice'].classes.has('hidden'));assert.equal(f.requests.filter(r=>r.url==='/api/rooms').length,1);});

test('removal cancel, escape and backdrop submit no request and restore focus',async()=>{const f=setup();const trigger=f.el['open-add-room'];f.run("removeRoom({key:'keep',title:'same',transport:'loco',chat_id:'1002'},document.getElementById('open-add-room'))");assert.equal(f.el['remove-room'].open,true);assert.equal(f.el['remove-room-identity'].textContent,'방 ID 1002');f.el['cancel-remove-room'].events.click();assert.equal(f.el['remove-room'].open,false);assert.equal(trigger.focused,true);f.run("removeRoom({key:'keep',title:'legacy',conversation_id:'name:legacy'})");assert.ok(f.el['remove-room-identity'].textContent.includes('이름 기반 연결'));let prevented=false;f.el['remove-room'].events.cancel({preventDefault(){prevented=true}});assert.equal(prevented,true);assert.equal(f.el['remove-room'].open,false);f.run("removeRoom({key:'keep',title:'same'})");f.el['remove-room'].events.click({target:f.el['remove-room'],clientX:0,clientY:0});assert.equal(f.el['remove-room'].open,false);assert.equal(f.requests.filter(r=>r.url==='/api/rooms/remove').length,0);});
test('removal confirmation submits exact key once and reports success',async()=>{const f=setup();f.run("removeRoom({key:'exact-1002',title:'same',transport:'loco',chat_id:'1002'})");assert.equal(f.requests.length,0);await f.el['confirm-remove-room'].events.click();const requests=f.requests.filter(r=>r.url==='/api/rooms/remove');assert.equal(requests.length,1);assert.deepEqual(JSON.parse(requests[0].opt.body),{key:'exact-1002'});assert.equal(f.el['remove-room'].open,false);assert.ok(f.el['error-notice'].textContent.includes('등록을 제거했어요'));assert.ok(f.el['error-notice'].textContent.includes('카카오톡 방은 그대로'));});
test('pending removal disables actions, ignores repeat click and escape, then restores controls',async()=>{const f=setup();f.mode('remove-loading');f.run("removeRoom({key:'one',title:'same'})");const pending=f.run('confirmRemoval()');assert.equal(f.el['confirm-remove-room'].disabled,true);assert.equal(f.el['cancel-remove-room'].disabled,true);await f.run('confirmRemoval()');f.el['remove-room'].events.cancel({preventDefault(){}});assert.equal(f.el['remove-room'].open,true);assert.equal(f.requests.filter(r=>r.url==='/api/rooms/remove').length,1);f.release();await pending;assert.equal(f.el['remove-room'].open,false);assert.equal(f.el['confirm-remove-room'].disabled,false);});
test('failed removal preserves saved room state and never claims removal or auto retries',async()=>{const f=setup();f.mode('remove-error');f.run("var preserved={key:'saved',title:'same',approved:true,yui:true,yumi:false};roomsData.rooms=[preserved];removeRoom(preserved)");await f.run('confirmRemoval()');assert.equal(f.el['remove-room'].open,true);assert.equal(f.run('roomsData.rooms.length'),1);assert.equal(f.run('preserved.approved'),true);assert.equal(f.run('preserved.yui'),true);assert.equal(f.el['confirm-remove-room'].disabled,false);assert.ok(f.el['remove-room-status'].textContent.includes('완료를 확인하지 못했어요'));assert.ok(!(f.el['error-notice']?.textContent||'').includes('제거했어요'));assert.equal(f.requests.filter(r=>r.url==='/api/rooms/remove').length,1);});
test('HTTP200 removed:false remains failure and disconnected origin focuses add button',async()=>{const f=setup();f.mode('remove-held');f.run("removeRoom({key:'kept',title:'same'})");await f.run('confirmRemoval()');assert.equal(f.el['remove-room'].open,true);assert.ok(f.el['remove-room-status'].textContent.includes('확인하지 못했어요'));f.run('removalFocus={isConnected:false};cancelRemoval()');assert.equal(f.el['open-add-room'].focused,true);});
